## configuration file to be used by snakemake

# Structure
# ├──.gitignore
# ├── README.md
# ├── LICENSE.md
# ├── workflow
# ├    ├── report
# ├    ├── results
# ├    ├    ├── trimmedReads
# ├    ├        ├ unpairedReads
# ├    ├    ├── star
# ├    ├        ├── firstPass
# ├    ├        ├── secondPass
# ├    ├    ├── picard
# ├    ├    ├── salmon
# ├    ├    ├── freebayes
# ├    ├    ├── rseqc
# ├    ├        ├── bam_stats
# ├    ├        ├── junction_annotation
# ├    ├        ├── geneBody_coverage   
# ├    ├── logs
# ├    ├── envs
# ├    ├── indeces
# ├    ├    ├── genome
# ├    ├    ├── transcriptome
# ├    ├── references
# ├        ├── genome
# ├        ├── transcriptome
# ├        ├── annotation
# ├        ├── adapter
# ├── config
# ├    ├── config.yaml
# ├── Snakefile


## 1. Experiment name
experiment: DevelopingInflorescence

## 2. Path to sample sheet (csv format)
samplesheet: config/samples.csv

## 3. Ending of your paired end reads, in this example the files are named A1da.R1 and A1da.R2
reads: [".R1", ".R2"]

## 4. Ending of your paired end reads input
ending: .fq.gz

############## All the following files need to be located in workflow/references
## 5. Coordinates of the split barley chromosome for input into freebayes-parallel 
genomeCoordinates: splitChromosomes

## 6. Reference genome name to be used for mapping (assumes .fasta ending)
genome: barke_split.fasta

## 7. Reference transcriptome name to be used for mapping (assumes .fasta.gz ending)
## The pipeline assumes decoy mode, therefore the following lines need to be run and the decoys.txt and decoys.txt.bak
## added to the workflow/references folder
    # grep "^>" < barke_split.fasta | cut -d " " -f 1 > decoys.txt
    # sed -i.bak -e 's/>//g' decoys.txt
    # cat BartV1BarkeNoDups.fasta barke_split.fasta | pigz -c - > gentrome.fasta.gz
transcriptome: gentrome.fasta.gz

## 8. Bed file for transcript location on genome
transcriptCoordinates: BartOnBarkeSplit.bed

